# Generated by Django 4.2.1 on 2023-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_createuser_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
