# Generated by Django 4.2.1 on 2023-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_createuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createUser',
        ),
    ]
